# Generated by Django 3.1 on 2020-12-11 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_passby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='city',
        ),
        migrations.RemoveField(
            model_name='student',
            name='passby',
        ),
    ]
